### ISSUE TITLE
Using mapFormat with non-primitives explodes

### ISSUE THREAD

**Issue by dwijnand** [eed3si9n/sjson-new#24]
Adding this test-case to `sjsonnew.support.spray.CollectionFormatsSpec`, in `"The mapFormat" should`:

```scala
"round trip a Map[Person, Int]" in assertRoundTrip(Map(person -> 1))
```

```scala
  def assertRoundTrip[A: JsonWriter: JsonReader](x: A) = {
    val jValue: JsValue = Converter.toJsonUnsafe(x)
    val y: A = Converter.fromJsonUnsafe[A](jValue)
    x mustEqual y
  }
```

blows up with this:

```
[error]   ! round trip a Map[Person, Int]
[error]    sjsonnew.SerializationException: Unexpected builder state: InObject (package.scala:19)
[error] sjsonnew.package$.serializationError(package.scala:19)
[error] sjsonnew.Builder.stateError(Builder.scala:184)
[error] sjsonnew.Builder.beginObject(Builder.scala:111)
[error] sjsonnew.support.spray.CollectionFormatsSpec$PersonFormat$.write(CollectionFormatsSpec.scala:30)
[error] sjsonnew.support.spray.CollectionFormatsSpec$PersonFormat$.write(CollectionFormatsSpec.scala:28)
[error] sjsonnew.CollectionFormats$$anon$3$$anonfun$write$3.apply(CollectionFormats.scala:96)
[error] sjsonnew.CollectionFormats$$anon$3$$anonfun$write$3.apply(CollectionFormats.scala:94)
[error] sjsonnew.CollectionFormats$$anon$3.write(CollectionFormats.scala:94)
[error] sjsonnew.CollectionFormats$$anon$3.write(CollectionFormats.scala:88)
[error] sjsonnew.SupportConverter$class.toJsonUnsafe(SupportConverter.scala:23)
[error] sjsonnew.support.spray.Converter$.toJsonUnsafe(Converter.scala:6)
[error] sjsonnew.support.spray.CollectionFormatsSpec.assertRoundTrip(CollectionFormatsSpec.scala:119)
[error] sjsonnew.support.spray.CollectionFormatsSpec$$anonfun$3$$anonfun$apply$22.apply(CollectionFormatsSpec.scala:90)
[error] sjsonnew.support.spray.CollectionFormatsSpec$$anonfun$3$$anonfun$apply$22.apply(CollectionFormatsSpec.scala:90)
```

**Comment by dwijnand** [comment]
I'm not clear enough on sjson-new's infrastructure to understand how/where to fix this.

@eed3si9n any ideas?

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/sjson-new/blob/v0.5.1/core/src/main/scala/sjsonnew/CollectionFormats.scala#L84-L87

```
  /**
    * Supplies the JsonFormat for Maps. The implicitly available JsonFormat for the key type K must
    * always write JsStrings, otherwise a [[sjsonnew.SerializationException]] will be thrown.
   */
```

**Comment by dwijnand** [comment]
So I need a competing JsonFormat for Person or ModuleId for when it's required by mapFormat? How do I do that? Btw I didn't write JsonFormat for ModuleId. It's auto generated by sbt-datatype and mixed into LibraryManagementCodec, and potentially required transitively in some other datatype like UodateReport or something.

How do we fix this?

**Comment by dwijnand** [comment]
Here's one https://github.com/sbt/sbt/blob/8a9ce1bf13d8c1af4e21100e8344a263a956168e/main/src/main/scala/sbt/Defaults.scala#L1596

**Comment by dwijnand** [comment]
Also https://github.com/sbt/sbt/blob/8a9ce1bf13d8c1af4e21100e8344a263a956168e/main/src/main/scala/sbt/Defaults.scala#L1436

**Comment by eed3si9n** [comment]
so we just need a custom codec for `ModuleID`?

**Comment by dwijnand** [comment]
How did it work with sbinary?

**Comment by eed3si9n** [comment]
I'm guessing that sbinary encoded it as sequence, but `Map` in sjson-new is used to create JObject `{ "key": value }` style.

**Comment by dwijnand** [comment]
Perhaps mapFormat should take a (new) JsonStringFormat instead of accepting any JsonFormat at compile time and failing at runtime.

**Comment by eed3si9n** [comment]
I was thinking the same thing.

**Comment by dwijnand** [comment]
https://github.com/circe/circe/blob/v0.7.0-M1/modules/core/shared/src/main/scala/io/circe/KeyEncoder.scala
