### ISSUE TITLE
Reconsider the highly fragile Builder

### ISSUE THREAD

**Issue by dwijnand** [eed3si9n/sjson-new#32]
It's way too simple to create or compose JsonFormat instances that end up throwing runtime errors.

Here's a sample when running sbt/sbt's "actions/all" scripted test:

```
[info] sjsonnew.SerializationException: Unexpected builder state: End
[info]     at sjsonnew.package$.serializationError(package.scala:19)
[info]     at sjsonnew.Builder.stateError(Builder.scala:184)
[info]     at sjsonnew.Builder.beginArray(Builder.scala:66)
[info]     at sbt.internal.util.HListFormat$$anon$2.write(HListFormat.scala:25)
[info]     at sbt.internal.util.HListFormat$$anon$2.write(HListFormat.scala:23)
[info]     at sbt.internal.util.HListFormat$$anon$2.write(HListFormat.scala:27)
[info]     at sbt.internal.util.HListFormat$$anon$2.write(HListFormat.scala:23)
[info]     at sjsonnew.SupportConverter$class.toJsonUnsafe(SupportConverter.scala:23)
[info]     at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[info]     at sjsonnew.SupportConverter$$anonfun$toJson$1.apply(SupportConverter.scala:14)
[info]     at scala.util.Try$.apply(Try.scala:192)
[info]     at sjsonnew.SupportConverter$class.toJson(SupportConverter.scala:14)
[info]     at sjsonnew.support.scalajson.unsafe.Converter$.toJson(Converter.scala:7)
[info]     at sbt.internal.util.PlainOutput.write(Output.scala:15)
[info]     at sbt.internal.util.FileBasedStore$$anonfun$write$1.apply(CacheStore.scala:39)
[info]     at sbt.internal.util.FileBasedStore$$anonfun$write$1.apply(CacheStore.scala:39)
[info]     at sbt.io.Using.apply(Using.scala:23)
[info]     at sbt.internal.util.FileBasedStore.write(CacheStore.scala:39)
[info]     at sbt.internal.util.Tracked$CacheHelp.save(Tracked.scala:58)
[info]     at sbt.internal.util.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:52)
[info]     at sbt.Classpaths$.cachedUpdate(Defaults.scala:1669)
[info]     at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1519)
[info]     at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1471)
```

I've hit this general problem in different manifestation over the last few weeks switching sbt's modules to sjson-new.

I've never run into these kinds of runtime errors when defining custom JSON typeclass instances using play-json.

**Comment by eed3si9n** [comment]
I agree with builder API being too low level in most cases.
I already created #12 for porting Play's DSL. In the interim, LList isomorphism could also be used.

**Comment by dwijnand** [comment]
Defining how a type is serialising to JSON should be as simple as https://www.playframework.com/documentation/2.5.x/ScalaJson#Using-Writes-converters

**Comment by eed3si9n** [comment]
Builder abstraction does have the benefit of performance and backend isolation. It's just not for most users to directly use it, and that's partially why Contraband exists.

**Comment by dwijnand** [comment]
It's should be generally easier to not make trivial mistakes (even when using Contraband, for types that are not defined using Contraband).

That should be a bigger priority than performance or backend isolation.

**Comment by dwijnand** [comment]
I'm not sure if this the same issue or a separate issue, but I've been hit by the fragility of the Unbuilder too:

```
[info] sjsonnew.DeserializationException: Expected Map as JsObject, but got JArray([Lscala.json.ast.unsafe.JValue;@45dd46fa)
[info] 	at sjsonnew.package$.deserializationError(package.scala:18)
[info] 	at sjsonnew.support.scalajson.unsafe.Converter$FacadeImpl$.extractObject(Converter.scala:111)
[info] 	at sjsonnew.support.scalajson.unsafe.Converter$FacadeImpl$.extractObject(Converter.scala:9)
[info] 	at sjsonnew.Unbuilder.beginPreObject(Unbuilder.scala:89)
[info] 	at sjsonnew.FlatUnionFormats$$anon$2.read(FlatUnionFormats.scala:120)
[info] 	at sbt.internal.util.HListFormat$$anon$2.read(HListFormat.scala:35)
```

The flat union formats assume that they are being called inside a JObject. But in the case of HListFormat, this isn't true, as HList's serialise to arrays. :-( :-1:

**Comment by dwijnand** [comment]
Btw this is what's causing `dependency-management/cache-update` to be broken.

**Comment by eed3si9n** [comment]
I think this points more to the difficulty in rolling out custom HList encoding.
I'd recommend projecting it to the date types that I've provided codecs for like tuples and LList.

**Comment by dwijnand** [comment]
No. I think it's a mistake to blame the choice of how HList wishes to serialise itself to JSON.

If you use another type, that also encodes to a JSON array, which contains types that are have flat union formats, you're going to run into the same runtime issues.

We should be leveraging the typesystem to encode these contraints, rather then have these incompatibilities clash and crash all over the place - I noticed also the:

> *BEWARE*:  A1,  A2 must be a concrete leaf type, and not an interface.

on the flat union formats - another way in which things can blow up at runtime.
