### ISSUE TITLE
Reconsider the name of the "project" method on AdditionalFormats

### ISSUE THREAD

**Issue by dwijnand** [eed3si9n/sjson-new#41]
AdditionalFormats is mixed into BasicJsonProtocol (and from there into other implicit cakes).

This means that importing `sjsonew.BasicJsonProtocol._` will make `project` ambiguous between sbt's (macro) method) and this method.

I found this in fixing scripted tests when switching from sbinary to sjsonnew.

Feel free to close if you consider this a non-issue.

**Comment by eed3si9n** [comment]
Yea. Since these are frequently imported, I'm ok with adding prefixes like `projectFormat` and `liftFormat`.
