### ISSUE TITLE
LList's purpose

### ISSUE THREAD

**Issue by dwijnand** [eed3si9n/sjson-new#43]
`LList` proports itself as a "Heterogeneous list with labels", but if you look at the definition of `LCons`:

```scala
final case class LCons[A1: JsonFormat: ClassManifest, A2 <: LList: JsonFormat](
    name: String, head: A1, tail: A2
) extends LList {
  // ..
}
```

.. it's defined in terms of types for which there exist `JsonFormat` instances (and it captures them).

LList should either change its description, and possibly even its name, or it shouldn't capture `JsonFormat` instances.

**Comment by dwijnand** [comment]
For a little more context, I discovered this while spending a few seconds too many perplexed, trying to decipher an "implicit not found" error, until I realised it was associated to the `:*:` on `LNil`/`LCons`.

**Comment by eed3si9n** [comment]
It is heterogeneous list (of serializable stuff) with labels.
