### ISSUE TITLE
a field with empty Vector value gets omitted

### ISSUE THREAD

**Issue by eed3si9n** [eed3si9n/sjson-new#83]
## steps

Make an object with a Vector field, serialize it to JSON.

## problem

The field is omitted. For example, in the following example, `"diagnostics": []` is missing.

```
JsonRpcNotificationMessage(2.0, textDocument/publishDiagnostics, {"uri":"file:/xxx/Hello.scala"})
```

The receiver of the message is not happy.

## expectation

Empty fields are not omitted.

## notes

This was an intentional design added in #6.
I think `Option[A]` can continue to elide.

**Comment by dwijnand** [comment]
https://github.com/eed3si9n/sjson-new/pull/72

**Comment by eed3si9n** [comment]
Yea, I was wrong on this design decision. I still do think we need some way of evolving the JSON schema while remaining bincompat on Scala side. I'll go back to the drawing board.
